### PR TITLE
Limit number of materials to one except for final_finish

### PR DESCRIPTION
**Pull request by gingermusketeer**
Only final finish is expected to be composed of multiple materials the rest of the layers should only have at most one material.

### CODE REVIEW

**Comment by gingermusketeer** [comment]
@tojanpedersen Any thoughts on this?

**Comment by tojanpedersen** [comment]
With the introduction of IMS we may have the same issue as ENIG - we may have to specify base material (Aluminium type or copper type), Insulation layer properties and copper.
IMS is buit like this:

Copper
Insulation layer
Base material/metal

**Comment by gingermusketeer** [comment]
@tojanpedersen What layer functions does the IMS material apply to?

**Comment by tojanpedersen** [comment]
Layer 1: Copper = same as normal copper
Layer2: Insulation layer - this is dielectric and a major parameter is Thermal conductivity: Typical values:
1-8 W/mK (default can be 2W/mK) There are many different values in the market like 1.3, 2.2 so a list is not easy to make. A normal requirement is  >= xx  
Layer 3: Metal - it can be Steel, Aluminium and copper. Standards/specification of the metal:
Aluminium: 1100H14, 5052H34, 6061T6, 1060 H18
Copper: C1100, C1220
Stainless steel: SUS430

Other parameters still applies like thickness and tolerances.

**Comment by alydersen** [comment]
@tojanpedersen The combination that the IMS requires are actually part of the buildup, like core and prepress. We can easily facilitate the need for that there. I suggest we go ahead with this merge

**Review by tojanpedersen — APPROVED** [review]
Approved based on standard build structure

**Pull request merged**
